const plantsdatabaseweeds = [
    {name: "Dandelion", sciname: "Taraxacum officinale", family: "daisy", commonness: "very common", tags: "",
description: ""},
    {name: "Burdock", sciname: "Arctium lappa", family: "daisy",commonness: "very common", tags: ""},
    {name: "Goldenrod", sciname: "Solidago (group)", family: "daisy", commonness: "very common", tags: ""},
    {name: "Garlic Mustard", sciname: "Alliaria petiolata", family: "mustard", commonness: "very common", tags: ""},
    {name: "Wild Ginger", sciname: "Asarum (group)", family: "birthwort", commonness: "common", tags: ""},
    {name: "Blue Violet", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Cattail", sciname: "Typha (group)", family: "cattail", commonness: "common", tags: ""},
    {name: "Broadleaf Plantain", sciname: "Plantago major", family: "plantain", commonness: "very common", tags: ""},
    {name: "Asparagus", sciname: "Asparagus acutifolius", family: "asparagus", commonness: "rare", tags: ""},
    {name: "Red Baneberry", sciname: "Actaea rubra", family: "buttercup", commonness: "rare", tags: "poisoneat"},
    {name: "White Baneberry", sciname: "Actaea pachypoda", family: "buttercup", commonness: "very rare", tags: "poisoneat"},
    {name: "Mayapple", sciname: "Podophyllum peltatum", family: "barberry (Berberidaceae)", commonness: "rare", tags: "mature"},
    {name: "Clear Weed", sciname: "Pilea pumila", family: "nettle", commonness: "common", tags: ""},
    {name: "Stinging Nettle", sciname: "", family: "nettle", commonness: "very common", tags: "thorns"},
    {name: "Wood Nettle", sciname: "", family: "nettle", commonness: "common", tags: "thorns"},
    {name: "Purslane", sciname: "Portulaca oleracea", family: "", commonness: "very common", tags: ""},
    {name: "Spotted Spurge", sciname: "", family: "", commonness: "very common", tags: "toxic"},
    {name: "Sarsaparilla", sciname: "Aralia nudicaulis", family: "Araliaceae", commonness: "common", tags: ""},
    {name: "Woodsorrel", sciname: "Oxalis (group)", family: "", commonness: "very \common", tags: ""},
    {name: "Wild Carrot", sciname: "", family: "", commonness: "very common", tags: ""},
    {name: "Wild Parsnip", sciname: "", family: "", commonness: "common", tags: "poisonsap"},
    {name: "Wild Lettuce", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Buckthorn", sciname: "", family: "", commonness: "very common", tags: "toxic"},
    {name: "Witch Hazel", sciname: "", family: "", commonness: "very common", tags: ""},
    {name: "Yarrow", sciname: "Achillea millefolium", family: "daisy", commonness: "rare", tags: ""},
    {name: "Velvet Leaf", sciname: "Abutilon theophrasti", family: "Malvaceae", commonness: "common", tags: ""},
    {name: "Yellow Salsify", sciname: "Tragopogon dubius", family: "", commonness: "rare", tags: ""},
    {name: "Creeping Thistle", sciname: "Cirsium arvense", family: "daisy", commonness: "very common", tags: "thorns"},
    {name: "Sow Thistle", sciname: "Sonchus (group)", family: "daisy", commonness: "common", tags: ""},
    {name: "Globe Thistle", sciname: "Sonchus (group)", family: "daisy", commonness: "rare", tags: ""},
    {name: "Wild Strawberry", sciname: "Fragaria vesca", family: "rose (Rosaceae)", commonness: "common", tags: ""},
    {name: "Stickseed", sciname: "Hackelia virginiana", family: "borage", commonness: "", tags: ""},
    {name: "Pepperweed", sciname: "", family: "", commonness: "very common", tags: ""},
    {name: "Enchanters Nightshade", sciname: "Circaea lutetiana", family: "willowherb (Onagraceae)", commonness: "very common", tags: "toxic"},
    {name: "Mullein", sciname: "Verbascum thapsus", family: "figwort", commonness: "common", tags: ""},
    {name: "Motherwort", sciname: "Leonurus cardiaca", family: "mint", commonness: "", tags: ""},
    {name: "Milkweed", sciname: "Asclepias (group)", family: "dogbane", commonness: "very common", tags: ""},
    {name: "Horseweed", sciname: "Conyza canadensis", family: "daisy", commonness: "common", tags: ""},
    {name: "Curly Dock", sciname: "Rumex crispus", family: "knotweed", commonness: "rare", tags: ""},
    {name: "Bedstraw", sciname: "Galium (group)", family: "bedstraw", commonness: "common", tags: ""},
    {name: "Ragweed", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Giant Ragweed", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Chicory", sciname: "Cichorium", family: "daisy", commonness: "", tags: ""},
    {name: "Butterfly Weed", sciname: "Asclepias tuberosa", family: "dogbane", commonness: "rare", tags: ""},
    {name: "Chickweed", sciname: "Stellaria media", family: "pink (Caryophyllaceae)", commonness: "very common", tags: ""},
    {name: "Gooseberry", sciname: "Ribes (group)", family: "grossulariaceae", commonness: "rare", tags: "thorns"},
    {name: "Pineapple Weed", sciname: "Matricaria discoidea", family: "daisy", commonness: "very common", tags: "sent"},
    {name: "Catnip", sciname: "Nepeta cataria", family: "mint", commonness: "very common", tags: "sent"},
    {name: "Beebalm", sciname: "", family: "mint", commonness: "common", tags: "sent"},
    {name: "Birdsfoot Trefoil", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Blackberry", sciname: "Rubus ursinus", family: "rose (Rosaceae)", commonness: "common", tags: "thorns"},
    {name: "Black Eyed Susan", sciname: "", family: "", commonness: "commmon", tags: ""},
    {name: "Canadian Honewort", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Chives", sciname: "", family: "", commonness: "rare", tags: "sent"},
    {name: "Clover", sciname: "", family: "", commonness: "very common", tags: ""},
    {name: "Blueberry", sciname: "", family: "heath (Ericaceae)", commonness: "rare", tags: ""},
    {name: "Wild Onion", sciname: "Allium stellatum", family: "Amaryllidaceae", commonness: "rare", tags: "sent"},
    {name: "Ground Ivy", sciname: "Glechoma hederacea", family: "mint", commonness: "very common", tags: "sent"},
    {name: "American Germander", sciname: "", family: "mint", commonness: "", tags: ""},
    {name: "Orangefruit Horsegentian", sciname: "", family: "", commonness: "rare", tags: ""},
    {name: "Japanese Barberry", sciname: "", family: "", commonness: "rare", tags: ""},
    {name: "jackinthepulpit", sciname: "", family: "", commonness: "rare", tags: "poisonsap"},
    {name: "False Solomons Seal", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Spreading Dogbane", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Gray Dogwood", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Staghorn Sumac", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Red Elderberry", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Purple Coneflower", sciname: "", family: "Asteraceae", commonness: "", tags: ""},
    {name: "Yellow Coneflower", sciname: "", family: "Asteraceae", commonness: "", tags: ""},
    {name: "Poison Hemlock", sciname: "", family: "", commonness: "", tags: "poisonsap"},
    {name: "Cow Parsnip", sciname: "", family: "", commonness: "", tags: "poisoneat"},
    {name: "Common Tansy", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Cow Vetch", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Field Wormwood", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Ground Elder", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Honey suckle", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Jewelweed", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Mapleleaf Viburnum", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Woodland Sunflower", sciname: "", family: "", commonness: "", tags: ""},
];

const plantsdatabasevines = [
    {name: "Virginia Creeper", sciname: "", family: "", commonness: "very common", tags: ""},
    {name: "Riverbank Grape", sciname: "", family: "", commonness: "very common", tags: ""},
    {name: "Poisonivy", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Wild Cucumber", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Oriental Bittersweet", sciname: "", family: "", commonness: "common", tags: ""},
    {name: "Hog Peanut", sciname: "", family: "", commonness: "", tags: "common"},
    {name: "Hedge Bindweed", sciname: "", family: "", commonness: "", tags: "rare"},
];
const plantsdatabasemushrooms = [
    {name: "Artistconk", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Destroying Angel", sciname: "", family: "", commonness: "", tags: "poisoneat"},
    {name: "Pearshaped Puffball", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Shaggy Scalycap", sciname: "", family: "", commonness: "", tags: "poisoneat"},
    {name: "Turkey Tail", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Aspen Bracket", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Hoof Fungus", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Blushing Bracket", sciname: "", family: "", commonness: "", tags: ""},
]
const plantsdatabasetrees = [
    {name: "White Oak", sciname: "Quercus alba", family: "Fagaceae", commonness: "", tags: ""},
    {name: "Black Oak", sciname: "Quercus velutina", family: "Fagaceae", commonness: "", tags: ""},
    {name: "Bur Oak", sciname: "Quercus macrocarpa", family: "Fagaceae", commonness: "", tags: ""},
    {name: "Boxelder", sciname: "Acer negundo", family: "soapberry", commonness: "very common", tags: ""},
    {name: "Red Maple", sciname: "Acer rubrum", family: "soapberry", commonness: "", tags: ""},
    {name: "Red Pine", sciname: "Pinus resinosa", family: "pine", commonness: "", tags: ""},
    {name: "White Pine", sciname: "Pinus strobus", family: "pine", commonness: "", tags: ""},
    {name: "Cottonwood", sciname: "", family: "willow", commonness: "", tags: ""},
    {name: "Ash", sciname: "Fraxinus pennsylvanica", family: "olive (Oleaceae)", commonness: "", tags: ""},
    {name: "American Elm", sciname: "Ulmus americana", family: "ulmaceae", commonness: "", tags: ""},
    {name: "American Linden", sciname: "Tilia americana", family: "", commonness: "", tags: ""},
    {name: "Black Locust", sciname: "Robinia pseudoacacia", family: "pea (Fabaceae)", commonness: "", tags: ""},
    {name: "Black Cherry", sciname: "Prunus serotina", family: "rose (Rosaceae)", commonness: "", tags: ""},
    {name: "Choke Cherry", sciname: "Prunus virginiana", family: "rose (Rosaceae)", commonness: "", tags: ""},
    {name: "Black Walnut", sciname: "Juglans nigra", family: "walnut (Juglandaceae)", commonness: "", tags: ""},
    {name: "Butter Nut", sciname: "Juglans cinerea", family: "walnut (Juglandaceae)", commonness: "", tags: ""},
    {name: "Horse Chestnut", sciname: "Aesculus hippocastanum", family: "soapberry", commonness: "", tags: ""},
    {name: "Crab Apple", sciname: "", family: "", commonness: "", tags: ""},
    {name: "White Mulberry", sciname: "Morus alba", family: "mulberry (Moraceae)", commonness: "", tags: ""},

]
const plantsdatabaseother = [
    {name: "Wolfs Milk", sciname: "", family: "", commonness: "", tags: ""},
    {name: "Powdery Mildew", sciname: "", family: "", commonness: "very common", tags: ""},
]



const plantsdatabase = [
    {tablename: "weed", table: plantsdatabaseweeds, description: "Plants that popup everywhere."},
    {tablename: "vine", table: plantsdatabasevines, description: "Many vines will just be little shoots comming out of the ground. Most Vines produce Berries."},
    {tablename: "tree", table: plantsdatabasetrees, description: ""},
    {tablename: "mushroom", table: plantsdatabasemushrooms, description: ""},
    {tablename: "other", table: plantsdatabaseother, description: "Mold, Bacteria..."},
]
// Commonness (very common, common, rare, very rare)
