// Languages ------------------------------------------------------      
  
  const IrishLetters = [
  {letter: "s", sound: "sh / s", audio: "sh"},
  {letter: "t", sound: "ch / t", audio: "ch"},
  {letter: "d", sound: "j / d", audio: "j"},
  {letter: "l", sound: "li in million", audio: "lia"},
  {letter: "nn?", sound: "ny in canyon", audio: "ny"},
  {letter: "a", sound: "a in arm", audio: "a"},
  {letter: "á", sound: "a in caught", audio: "none"},
  {letter: "e", sound: "e in get", audio: "none"},
  {letter: "é", sound: "ay in pay", audio: "e"},
  {letter: "i", sound: "i in it", audio: "ischwa"},
  {letter: "í", sound: "ee in see", audio: "i"},
  {letter: "o", sound: "u in tug", audio: "none"},
  {letter: "ó", sound: "o in no", audio: "o"},
  {letter: "u", sound: "oo in good", audio: "none"},
  {letter: "ú", sound: "oo in cool", audio: "u"},
  {letter: "ae", sound: "ay in tay", audio: "none"},
  {letter: "ao/aoi", sound: "ee in see", audio: "i"},
  {letter: "ea", sound: "a in apple", audio: "aapple"},
  {letter: "eo", sound: "o in no", audio: "o"},
  {letter: "ei", sound: "e in set", audio: "none"},
  {letter: "eadh", sound: "e in set", audio: "none"},
  ]
  const Irishinfo = ["Broad Vowels (a o u) | Slender Vowels(e, i)"]
    const Ojibweinfo = ["d, k, p are softer (less breathy)"]
  const Hawaiianinfo = ["Don't glide the vowels like owww, just say o"]
  
  const TifinaghLetters = [
  {letter: "ⴱ", sound: "b", audio: "b"},
  {letter: "ⵀ", sound: "h", audio: "h"},
  {letter: "ⵃ", sound: "breathy h ح", audio: "hbreathy"},
  {letter: "ⴷ", sound: "d", audio: "d"},
  {letter: "ⴹ", sound: "ḍ ض", audio: "ddeep"},
  {letter: "ⴼ", sound: "f", audio: "f"},
  {letter: "ⴽ", sound: "k", audio: "k"},
  {letter: "ⵇ", sound: "q ق", audio: "qaf"},
  {letter: "ⴳ", sound: "g", audio: "g"},
  {letter: "ⵊ", sound: "j", audio: "j"},
  {letter: "ⵍ", sound: "l", audio: "llight"},
  {letter: "ⵎ", sound: "m", audio: "m"},
  {letter: "ⵏ", sound: "n", audio: "n"},
  {letter: "ⵔ", sound: "r tongue flap", audio: "rflap"},
  {letter: "ⵙ", sound: "s", audio: "s"},
  {letter: "ⵚ", sound: "ṣ ص", audio: "sdeep"},
  {letter: "ⵕ", sound: "deep r", audio: "none"},
  {letter: "ⵛ", sound: "sh", audio: "sh"},
  {letter: "ⵜ", sound: "t", audio: "t"},
  {letter: "ⵟ", sound: "ṭ ط", audio: "tdeep"},
  {letter: "ⵅ", sound: "clear throat خ", audio: "kh"},
  {letter: "ⵣ", sound: "z", audio: "z"},
  {letter: "ⵥ", sound: "ẓ ظ", audio: "zdeep"},
  {letter: "ⵊ", sound: "si in vision", audio: "zh"},
  {letter: "ⵄ", sound: "3 ع", audio: "a3"},
  
  {letter: "ⴰ", sound: "a", audio: "a"},
  {letter: "ⴻ", sound: "e", audio: "e"},
  {letter: "ⵉ", sound: "i", audio: "i"},
  {letter: "ⵢ", sound: "y", audio: "ya"},
  {letter: "ⵓ", sound: "u", audio: "u"},
  {letter: "ⵡ", sound: "w", audio: "wa"},
  ]    
  const AmharicLetters = [
    {letter: "ሀ", sound: "h", audio: "h"},
    {letter: "ሐ", sound: "h", audio: "h"},
    {letter: "ኀ", sound: "h", audio: "h"},
    {letter: "ኸ", sound: "h", audio: "h"},
    {letter: "ለ", sound: "L", audio: "llight"},
    {letter: "መ", sound: "m", audio: "m"},
    {letter: "ሠ", sound: "s", audio: "s"},
    {letter: "ሰ", sound: "s", audio: "s"},
    {letter: "ሸ", sound: "sh", audio: "sh"},
    {letter: "ቀ", sound: "k click", audio: "kclick"},
    {letter: "ጠ", sound: "t click", audio: "tclick"},
    {letter: "ጨ", sound: "ch click", audio: "chclick"},
    {letter: "ጰ", sound: "p click", audio: "pclick"},
    {letter: "ረ", sound: "r", audio: "rflap"},
    {letter: "በ", sound: "b", audio: "b"},
    {letter: "ቨ", sound: "v", audio: "v"},
    {letter: "ተ", sound: "t", audio: "t"},
    {letter: "ቸ", sound: "ch", audio: "ch"},
    {letter: "ነ", sound: "n", audio: "n"},
    {letter: "ኘ", sound: "ñ", audio: "ny"},
    {letter: "ከ", sound: "k", audio: "k"},
    {letter: "ወ", sound: "w", audio: "u"},
    {letter: "ዘ", sound: "z", audio: "z"},
    {letter: "ዠ", sound: "si in vision", audio: "zh"},
    {letter: "የ", sound: "y", audio: "i"},
    {letter: "ደ", sound: "d", audio: "d"},
    {letter: "ጀ", sound: "j", audio: "j"},
    {letter: "ገ", sound: "g", audio: "g"},
    {letter: "ጸ/ፀ", sound: "ts", audio: "ts"},
    {letter: "ፈ", sound: "f", audio: "f"},
    {letter: "ፐ", sound: "p", audio: "p"}
  ]
  const Amharicinfo = ["Abjad (attach vowels to consonants)"]
  
  const soundsdatabase = [
{name: "spanish", 
    arr: [
        {letter: "ñ", sound: "ny in canyon", audio: "ny"},
        {letter: "z", sound: "s", audio: "s"},
        {letter: "j", sound: "h", audio: "h"},
        {letter: "h", sound: "silent", audio: "none"},
        {letter: "l", sound: "lighter L (tongue touch top teeth)", audio: "llight"},
        {letter: "ll", sound: "y", audio: "ya"},
        {letter: "r", sound: "tongue flap", audio: "rflap"},
        {letter: "rr", sound: "roll", audio: "rroll"},
        {letter: "a", sound: "a in arm", audio: "a"},
        {letter: "e", sound: "eh", audio: "e"},
        {letter: "i", sound: "ee in see", audio: "i"},
        {letter: "o", sound: "o", audio: "o"},
        {letter: "u", sound: "u", audio: "u"}
      ], 
      info: ["Spanish is written how it's said!", "Don't glide the vowels like owww, just say o", "(Ci & Ce) the c sounds like s", "(Gi & Ge) g sounds like h", "qu sounds like k", "only roll r if its at the beginning or a word or 'rr'"]
},
{name: "portuguese", 
    arr: [
        {letter: "x", sound: "sh / z", audio: "sh"},
        {letter: "ch", sound: "sh", audio: "sh"},
        {letter: "lh", sound: "lli in million", audio: "lia"},
        {letter: "nh", sound: "ny in canyon", audio: "ny"},
        {letter: "r", sound: "tongue flap", audio: "rflap"},
        {letter: "rr", sound: "h", audio: "h"},
        {letter: "de", sound: "jee", audio: "none"},
        {letter: "ç", sound: "ss", audio: "none"}, 
        {letter: "ão", sound: "nasal ao", audio: "aonasal"},
        {letter: "õ", sound: "nasal o", audio: "onasal"},
        ], 
    info: ["L at the end of words sounds like w, 'Braziw' vs 'Brazil'", "s in middle of a word can sound like z 'casa'", "RR is a 'h' in brazil"]
},
{name: "russian",
    arr: [
        {letter: "Гг", sound: "g", audio: "g"},
        {letter: "Жж", sound: "g in genre", audio: "zh"},
        {letter: "Лл", sound: "L", audio: "l"},
        {letter: "Дд", sound: "d", audio: "d"},
        {letter: "Пп", sound: "p", audio: "none"},
        {letter: "Бб", sound: "b", audio: "b"},
        {letter: "Вв", sound: "v", audio: "v"},
        {letter: "Сс", sound: "s", audio: "s"},
        {letter: "Зз", sound: "z", audio: "z"},
        {letter: "Нн", sound: "n", audio: "n"},
        {letter: "Рр", sound: "r tongue flap", audio: "rflap"},
        {letter: "Хх", sound: "Kha", audio: "x"},
        {letter: "Фф", sound: "f", audio: "f"},
        {letter: "Цц", sound: "ts", audio: "ts"},
        {letter: "Чч", sound: "ch", audio: "ch"},
        {letter: "Шш", sound: "sh (heavy)", audio: "shheavy"},
        {letter: "Щщ", sound: "sh (light)", audio: "sh"},
        {letter: "Юю", sound: "yuu", audio: "yu"},
        {letter: "Яя", sound: "ya", audio: "ya"},
        {letter: "Кк!", sound: "k", audio: "k"},
        {letter: "Мм!", sound: "m", audio: "m"},
        {letter: "Тт!", sound: "t", audio: "t"},
        {letter: "Ее", sound: "ye", audio: "none"},
        {letter: "Ëë", sound: "yo", audio: "yo"},
        {letter: "Ээ", sound: "e", audio: "none"},
        {letter: "И/Й", sound: "i", audio: "i"},
        {letter: "Оо", sound: "o", audio: "none"},
        {letter: "Уу", sound: "u", audio: "u"},
        {letter: "Аа", sound: "a", audio: "a"},
        {letter: "ы", sound: "ui", audio: "a"}
      ],
    info: ["Ь makes the letter before it soft / add ye sound", "consonants and end of words are soft/faded", ]
},
{name: "german",
    arr: [
        {letter: "sch", sound: "sh", audio: "/ʃ/"},
        {letter: "st/sp", sound: "sh", audio: "ʃ"},
        {letter: "w", sound: "v", audio: "va"},
        {letter: "v", sound: "f", audio: "fa"},
        {letter: "ch", sound: "hiss", audio: "none"},
        {letter: "ß", sound: "s", audio: "s"},
        {letter: "ä", sound: "a in ape", audio: "aye"},
        {letter: "ö", sound: "o (close throat)", audio: "oclosethroat"},
        {letter: "ü", sound: "u (close throat)", audio: "uclosethroat"},
        {letter: "ie", sound: "ee in see", audio: "iː"},
        {letter: "ei", sound: "'eye'", audio: "ai"},
        {letter: "th", sound: "t", audio: "ta"},
        {letter: "eu", sound: "oi in oil", audio: "none"},
      ],
    info: ["ALL nouns are capitalized in German!"]
},
{name: "swedish",
    arr: [
        {letter: "sj/sk", sound: "hiss", audio: ""},
        {letter: "skj/stj", sound: "hiss", audio: ""},
        {letter: "a", sound: "a in saw", audio: ""},
      ],
    info: ["-tion, hiss sound + 'on'", "ch is hiss sound sometimes"]
},
{name: "finnish", 
    arr: [
        {letter: "c", sound: "s", audio: "s"},
        {letter: "j", sound: "y", audio: "ya"},
        {letter: "z", sound: "ts", audio: "ts"},
        {letter: "š", sound: "sh", audio: "sh"},
        {letter: "ž", sound: "j", audio: "j"},
        {letter: "ä", sound: "a in at", audio: "aapple"},
        {letter: "ö", sound: "like ir in girl", audio: "oclosethroat"},
        {letter: "å", sound: "oa", audio: "none"},
        ],
    info: ["Don't glide the vowels like owww, just say o"]
},
{name: "lakota",
    arr: [
        {letter: "š", sound: "sh", audio: "sh"},
        {letter: "č", sound: "ch", audio: "ch"},
        {letter: "Ĥ", sound: "brethy h???", audio: "none"},
        {letter: "ȟ", sound: "russian h", audio: "x"},
        {letter: "ǧ", sound: "Clear Throat", audio: "kh"},
        {letter: "ž", sound: "si in vision", audio: "zh"},
        {letter: "ŋ", sound: "ng in gong", audio: "ng"},
        {letter: "'", sound: "stop in uh-oh", audio: "stop"},
        {letter: "k'", sound: "k click", audio: "kclick"},
        {letter: "t'", sound: "t click", audio: "tclick"},
        {letter: "p'", sound: "p click", audio: "pclick"},
        {letter: "a", sound: "a in arm", audio: "a"},
        {letter: "e", sound: "e in bed", audio: "none"},
        {letter: "i", sound: "ee in see", audio: "i"},
        {letter: "o", sound: "o in no", audio: "o"},
        {letter: "u", sound: "oo in cool", audio: "u"},
        {letter: "aŋ", sound: "a (nasal)", audio: "anasal"},
        {letter: "iŋ", sound: "i (nasal)", audio: "inasal"},
        {letter: "uŋ", sound: "u (nasal)", audio: "unasal"},
      ], 
    info: ["(p, b, k) are weaker / unaspirated", "L is the same as english 'low'", "Don't glide the vowels like owww, just say o"]
},
{name: "polish", 
    arr: [
        {letter: "w", sound: "v", audio: "v"},
        {letter: "j", sound: "y", audio: "ya"},
        {letter: "c", sound: "ts", audio: "ts"},
        {letter: "ć/cz", sound: "ch", audio: "ch"},
        {letter: "ś/sz/si", sound: "sh", audio: "sh"},
        {letter: "dź/dż", sound: "j in just", audio: "j"},
        {letter: "dz", sound: "d + z", audio: "dz"},
        {letter: "ń/ni", sound: "ny in canyon", audio: "ny"},
        {letter: "ź/ż/rz", sound: "si in vision", audio: "zh"},
        {letter: "ch/h", sound: "kh", audio: "x"},
        {letter: "i", sound: "ee in see", audio: "i"},
        {letter: "y", sound: "i in sit", audio: "ischwa"},
        {letter: "o", sound: "o in no", audio: "o"},
        {letter: "u/ó", sound: "oo in cool", audio: "u"},
        {letter: "ą", sound: "nasal a", audio: "anasal"},
        {letter: "ę", sound: "nasal e", audio: "enasal"}
      ],
    info: [""]},
{name: "turkish", 
    arr: [
        {letter: "c", sound: "j in jar", audio: "j"},
        {letter: "ç", sound: "ch", audio: "ch"},
        {letter: "r", sound: "r tongue flap", audio: "rflap"},
        {letter: "ş", sound: "sh", audio: "sh"},
        {letter: "ö", sound: "er close throat", audio: "oclosethroat"},
        {letter: "ü", sound: "u close throat", audio: "uclosethroat"},
        {letter: "Iı", sound: "i in is", audio: "ischwa"},
        {letter: "İi", sound: "ee in see", audio: "i"},
        {letter: "e", sound: "e in bed", audio: "none"},
        {letter: "a", sound: "a in father", audio: "a"}
      ],
    info: [""]
},
{name: "oneida", 
    arr: [
        {letter: "k", sound: "g", audio: "gk"},
        {letter: "t", sound: "d", audio: "dt"},
        {letter: "ʌ", sound: "nasal a", audio: "anasal"},
        {letter: "sy", sound: "sh", audio: "sh"}
        ],
    info: ["(Tsy/Tsi) ts is j sound", "(Tshy/Tshi) tsh makes ch sound", "Don't glide the vowels like owww, just say o"]
},
{name: "ojibwe", 
    arr: [
        {letter: "a", sound: "a in about", audio: "none"},
        {letter: "aa", sound: "a in father", audio: "a"},
        {letter: "e", sound: "a in may", audio: "e"},
        {letter: "i", sound: "i in pin", audio: "ischwa"},
        {letter: "ii", sound: "ee in see", audio: "i"},
        {letter: "o", sound: "oo in book", audio: "none"},
        {letter: "oo", sound: "oo in cool", audio: "u"},
        {letter: "aanh", sound: "a (nasal)", audio: "anasal"},
        {letter: "enh", sound: "e (nasal)", audio: "enasal"},
        {letter: "iinh", sound: "ee (nasal)", audio: "inasal"},
        {letter: "oonh", sound: "oo (nasal)", audio: "unasal"},
        {letter: "'", sound: "stop in uh-oh", audio: "stop"},
        {letter: "zh", sound: "si in vision", audio: "zh"}
      ],
    info: [""]
},
{name: "hawaiian", 
    arr: [
        {letter: "w", sound: "v in vain", audio: "v"},
        {letter: "'", sound: "stop in oh-oh", audio: "stop"},
        {letter: "a", sound: "a in arm", audio: "none"},
        {letter: "e", sound: "eh", audio: "none"},
        {letter: "i", sound: "ee in see", audio: "none"},
        {letter: "o", sound: "no", audio: "none"},
        {letter: "u", sound: "oo in cool", audio: "none"},
        {letter: "ā", sound: "longer a", audio: "a"},
        {letter: "ē", sound: "longer e", audio: "e"},
        {letter: "ī", sound: "longer i", audio: "i"},
        {letter: "ō", sound: "longer o", audio: "o"},
        {letter: "ū", sound: "longer u", audio: "u"},
        ],
    info: [""]
},
{name: "arabic",
    arr: [
        {letter: "و", sound: "w / u", audio: "u"},
        {letter: "ي", sound: "y / ee", audio: "i"},
        {letter: "ن", sound: "n", audio: "n"},
        {letter: "ب", sound: "b", audio: "b"},
        {letter: "ت", sound: "t", audio: "t"},
        {letter: "ث", sound: "th in theory", audio: "th"},
        {letter: "ه", sound: "h", audio: "h"},
        {letter: "ح", sound: "breathy h", audio: "hbreathy"},
        {letter: "ج", sound: "si in vision", audio: "zh"},
        {letter: "خ", sound: "clear throat", audio: "kh"},
        {letter: "د", sound: "d", audio: "d"},
        {letter: "ذ", sound: "th voiced", audio: "thvoiced"},
        {letter: "س", sound: "s", audio: "s"},
        {letter: "ش", sound: "sh", audio: "sh"},
        {letter: "ص", sound: "s (deep)", audio: "sdeep"},
        {letter: "ض", sound: "d (deep)", audio: "ddeep"},
        {letter: "ط", sound: "t (deep)", audio: "tdeep"},
        {letter: "ظ", sound: "z (deep)", audio: "zdeep"},
        {letter: "ع", sound: "crazy ah", audio: "a3"},
        {letter: "غ", sound: "gh", audio: "gh"},
        {letter: "ف", sound: "f", audio: "f"},
        {letter: "ك", sound: "k", audio: "k"},
        {letter: "ق", sound: "q (throat k)", audio: "qaf"},
        {letter: "م", sound: "m", audio: "m"}
      ],
    info: ["Arabic is written from right to left!", "Each letter has 3 forms, beginning, middle, end", "Egypt (ق sounds like 'a'), (ج sounds like 'g')"]
},
{name: "hebrew",
    arr: [
        {letter: "א", sound: "a' / silent", audio: "none"},
        {letter: "י", sound: "y", audio: "i"},
        {letter: "בּ", sound: "b", audio: "b"},
        {letter: "ב", sound: "v", audio: "v"},
        {letter: "ו", sound: "v", audio: "v"},
        {letter: "ג", sound: "g", audio: "g"},
        {letter: "ד", sound: "d", audio: "d"},
        {letter: "ה", sound: "h", audio: "h"},
        {letter: "ז", sound: "z", audio: "z"},
        {letter: "ת", sound: "t", audio: "t"},
        {letter: "ט", sound: "t", audio: "t"},
        {letter: "ק", sound: "k", audio: "k"},
        {letter: "כּ (ךּ)", sound: "k", audio: "k"},
        {letter: "כ (ך)", sound: "clear throat", audio: "kh"},
        {letter: "ח", sound: "clear throat", audio: "kh"},
        {letter: "ל", sound: "L", audio: "llight"},
        {letter: "מ (ם)", sound: "m", audio: "m"},
        {letter: "נ (ן)", sound: "n", audio: "n"},
        {letter: "ע", sound: "a' \ silent", audio: "none"},
        {letter: "(ף) פ", sound: "f", audio: "f"},
        {letter: "(ףּ) פּ", sound: "p", audio: "p"},
        {letter: "(ץ) צ", sound: "ts", audio: "ts"},
        {letter: "ר", sound: "french R", audio: "none"},
        {letter: "שׁ", sound: "sh", audio: "sh"},
        {letter: "שׂ", sound: "s", audio: "s"},
        {letter: "ס", sound: "s", audio: "s"},
        {letter: "תּ / ת", sound: "s", audio: "s"}
      ],
    info: ["written right to left, letter inside the () is how it looks at end of a word ", "The א is either 'a' or silent"]
},
];

function getcurrentsoundobj(){
    let rr = null;
soundsdatabase.forEach(o => {
if(o.name.toLowerCase() == localStorage.getItem('currentlang').toLowerCase()){rr = o.arr};
})
return rr;
}